#!/usr/bin/env python2

import sys
import re
import datetime

data = sys.stdin.readlines()

def key(line):
    date = re.match(r'.*;.*?\[(=|)([0-9-]+)]', line)
    if not date:
         return datetime.datetime(2038, 1, 1)
    groups = date.groups()
    if not groups:
         return datetime.datetime(2038, 1, 1)
    return datetime.datetime.strptime(groups[1], "%Y-%m-%d")

print ''.join(sorted(data, key=lambda line: key(line)))
