#!/usr/bin/env python

import datetime
import ledger
import os
import sys
sys.path.append(os.path.dirname(__file__))
import common


s = common.Settings.load_or_defaults(os.path.expanduser("~/.ledgerhelpers.ini"))
journal = common.Journal.from_file(common.find_ledger_file(),
                                   common.find_ledger_price_file())
accts, commodities = journal.accounts_and_last_commodities()


when = common.prompt_for_date(
    sys.stdin, sys.stdout,
    "When?",
    s.get("last_date", datetime.date.today())
)
if when == datetime.date.today():
    del s["last_date"]
else:
    s["last_date"] = when

asset1 = common.prompt_for_account(
    sys.stdin, sys.stdout,
    accts, "From where?",
    s.get("last_withdrawal_account", None)
)
assert asset1, "Not an account: %s" % asset1
s["last_withdrawal_account"] = asset1
asset1_currency = commodities.get(asset1, ledger.Amount("$ 1"))

asset2 = common.prompt_for_account(
    sys.stdin, sys.stdout,
    accts, "To where?",
    s.get("last_deposit_account", None)
)
assert asset2, "Not an account: %s" % asset2
s["last_deposit_account"] = asset2
asset2_currency = commodities.get(asset2, ledger.Amount("$ 1"))

amount1 = common.prompt_for_amount(
    sys.stdin, sys.stdout,
    "How much?", asset1_currency
)

amount2 = common.prompt_for_amount(
    sys.stdin, sys.stdout,
    "What was deposited?", asset2_currency
)

lines = journal.generate_record("Withdrawal", when, None, [
    (asset1, [-1*amount1]),
    (asset2, [amount2]),
])
print "========== Record =========="
print "\n".join(lines)
save = common.yesno(
    sys.stdin, sys.stderr,
    "Hit ENTER or y to save it to the file, BACKSPACE or n to skip saving: "
)
if save:
    journal.add_lines_to_file(lines)
